# Generated by Django 3.2.11 on 2022-05-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('vehicle_plate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NavRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(editable=False)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_record', to='vehicle.vehicle')),
            ],
        ),
    ]
